appname="MyUnknownProject"
appver="1.0"
appcode="1"
appsdk="15"
path_pattern=""
packagename="com.myproject.unknown"
theme="Theme"
app_key=""
app_channel=""
developer=""
description=""
debugmode=false
user_permission={
  "INTERNET",
 "WRITE_EXTERNAL_STORAGE"
 --非默认情况下请手动添加权限
}
